### ISSUE TITLE
Black artifacts on iPhone 11 Pro's video record from front camera

### ISSUE THREAD

**Issue by CheshireCat92** [gorastudio/SCNRecorder#11]
The issue occurs when recording AR video from the front camera to the iPhone 11 Pro Max. Less often on Xs Max.
How to do it again: You have to try to record short videos quickly.  The principle of shooting video is the same as with Instagram - press the button, video is shot. Release the button - the recording is complete. 
An example code will be provided if necessary.

**Comment by CheshireCat92** [comment]
Update: link to source files -> https://drive.google.com/file/d/1m8DN83tztB7Mmw4o9jyw9i-SwVpirWRZ/view?usp=sharing

**Comment by v-grigoriev** [comment]
It seems that the fix is to set the `framebufferOnly` flag for CAMetalLayer to false near the `prepareForRecording` call, e.g. in the `viewDidLoad`.
The SCNRecorder does the same thing a moment before starting recording to not affect performance. But seems on the new devices it produces artifacts.
So far it was only reproduced only on a few devices. The fix will be included in the SCNRecorder if there are more cases or stable reproduction.
